### ISSUE TITLE
canon_pixma.conf missing in /etc/sane.d/

### ISSUE THREAD

**Issue by insomniacno1** [Ordissimo/scangearmp2#35]
Xubuntu 16.04 64bit, after following the instructions here and on the https://launchpad.net/~thierry-f/+archive/ubuntu/fork-michael-gruz

1. Head over to https://launchpad.net/~thierry-f/+archive/ubuntu/fork-michael-gruz and install the ppa as described:

sudo add-apt-repository ppa:thierry-f/fork-michael-gruz
sudo apt-get update

This updated the Scangearmp2 to 4.10

2. Your instruction on how to activate the backend  came up with error about not being allowed - So go to /etc/sane.d/ and edit dll.conf as root using geany. Under canon, add canon_pixma and save the document and close the editor.

3. Open terminal and type sudo sane-find-scanner – it will not find the scanner as it is on network and not USB

4. In terminal type scanimage -L – scanner is now found and all SANE apps work.

user@user:~$ scanimage -L
device `canon_pixma:74-38-B7-87-E6-94' is a CANON MG3000 series flatbed scanner
user@user:~$ scanimage -V
scanimage (sane-backends) 1.0.31-269-gc85185bd4; backend version 1.0.31

SANE works(Aquireimages, simple scan, xsane, skanlite) and find the scanner, but LibreOffice Writer (any version, currently 7.0.4.2 snap) can't find the scanner. In Writer I click on insert-Media-Scan-Select source and nothing happens. 

Could the reason be the missing canon_pixma.conf backend?

Could you make the canon_pixma.conf file for download or list it in the readme?

Thank you in advance

Jan

**Comment by Ordissimo** [comment]
Hi  @insomniacno1,
I looked at it, I reviewed the packaging, I did it wrong for version 4.10.
Can you uninstall scangearmp2 and install the new version : 
```
sudo apt purge scangearmp2
sudo apt update
sudo apt install scangearmp2
```

**Comment by Ordissimo** [comment]
I close the ticket, there were some packagind problems.
This is solved!

**Comment by insomniacno1** [comment]
Hi Ordissimo, Unfortunately I still can't scan into LibreOffice writer 7.0, everything is as described above and still not canon_pixma.conf in sane.d

there is canon.conf and there is pixma.conf Could it be the driver is addressing the wrong .conf file?

# pixma.conf configuration for the sane pixma backend
#
# disable network scanner detection.
# This must be the first not commented line
# Uncomment the following line:
# networking=no
#
# bjnp-timeout=5000
# Specify the timeout (in ms) to be used for all the following
# scanners.
# May be specified multiple times.
# The last value (if any) will be used for auto-detection
#
# define URI's of scanners (one per line)
# This is only used for network scanners.
# normally scanners will be detected by sending a broadcast
# if this does not work under your OS, or if the scanners
# are on a different subnet, configure your scanners URI here
#
# method must be bjnp
# port number can normally be left out, port 8612 is used as default
# The timeout parameter sets a timeout value for the scanner on
# the same line
# Examples using bjnp:
# bjnp://myscanner.my.domain:8612 // uses the default 1000ms timeout
# bjnp-timeout=5000
# bjnp://printer-1.pheasant.org // will use the 5000 ms timeout
# bjnp://scanner.bad-network.org/timeout=1500 // timeout set to 1500 ms
# bjnp-timeout=3000 // will be used for auto-detected scanners
#
# Example using for a scanner using mfnp including the optional timeout:
# mfnp://scanner.bad-network.org/timeout=1500

As I said before, SANE and all the other apps listed above work with the scanner, only LibreOffice can't find anything or maybe not even searching.

Hope we can figure this one out together:)

Jan

**Comment by Ordissimo** [comment]
I remind you that the proposed driver is based on code not available furnace by gun, it allows to use the proprietary driver with sane-backend.
The configuration files always provided by canon are here => `/usr/lib/x86_64-linux-gnu/bjlib/`
Can you use your scanner with simple-scan or xsane?

**Comment by Ordissimo** [comment]
I invite you to look for the problem where it happens, open a bug at libreoffice.
This is the message I get when I try to scan:  `/opt/libreoffice7.1/program/soffice.bin: symbol lookup error: /usr/lib/x86_64-linux-gnu/sane/libsane-sp_330_3710_series.so.1: undefined symbol: sanei_config_open`

**Comment by insomniacno1** [comment]
So meaning you can't scan into LibreOffice either?

Yes all SANE programs work fine (Aquireimages, simple scan, xsane, skanlite, scangear)

I do have a bug report here [https://bugs.documentfoundation.org/show_bug.cgi?id=140435](url)

**Comment by Ordissimo** [comment]
With libreoffice6.4 I can scan with the ESCL driver.
On ubuntu 20.04, I downloaded the last version of libreoffice7.1, I can't scan. I noted the error encountered.
Add my feedback and the link on the open issue on scangearmp2, it gives a start answer to the problem.

**Comment by Ordissimo** [comment]
I withdrew the Ricoh pilot who was planting libreoffice.
So I confirm that the canon_pixma, imagescan and escl driver works correctly in libreoffice.

![IMG_20210308_154821](https://user-images.githubusercontent.com/10682892/110338246-13d8fe80-8027-11eb-95e6-4d523adb2f0d.jpg)

**Comment by insomniacno1** [comment]
> I withdrew the Ricoh pilot who was planting libreoffice.
> So I confirm that the canon_pixma, imagescan and escl driver works correctly in libreoffice.
> 
> ![IMG_20210308_154821](https://user-images.githubusercontent.com/10682892/110338246-13d8fe80-8027-11eb-95e6-4d523adb2f0d.jpg)

Hi Ordisimo, not quite sure what you mean by this?

Jan

**Comment by Ordissimo** [comment]
scanning with Libreoffice6.4 and libreoffice7.1 using the canon_pixma driver works.

**Comment by insomniacno1** [comment]
Yeah, but what did you mean that you "withdrew the Ricoh pilot who was planting LibreOffice? I don't understand

**Comment by Ordissimo** [comment]
This concerns my installation.
Not yours.
If it works you have to search in your installation.

**Comment by insomniacno1** [comment]
Hi Ordissimo,

Version: 7.1.2.2 / LibreOffice Community
Build ID: 5751006d328844ba3fa6124ed263bbf122f0788a
CPU threads: 2; OS: Linux 4.4; UI render: default; VCL: gtk3
Locale: en-GB (en_GB.UTF-8); UI: en-US
Calc: threaded

Even after update I still can't scan into Lo writer.

With kind regards

Jan

**Comment by Ordissimo** [comment]
Hi @insomniacno1 ,

 Can you launch libreoffice in console and send me the oog after I want to scan?

**Comment by insomniacno1** [comment]
I'm starting over, can you tell me which versions of Libreoffice you have. 6.4.???? 7.1.???? and is that installed or snap or appimage, I tried uninstalling the snap version of 7.1.2.2 installing it again by downloading the latest version, then unpacking it and go to DEBS folder and open terminal, then install by 

sudo dpkg -i *.deb

After installing it showed up in my App menu but wouldn't open, seem to be a problem with GTK3

So I uninstalled it and purged it.

I tried installing the old version of Writer 6.2.8rc in my Ubuntu Software centre(center), but that wouldn't open either, now I'm trying the one I had before 6.4.7, installing it through terminal. If not working I will try the app image or if I can find an older snap.

I will let you know what happens.

Attached is screenshot of what happened when trying to open Libreoffice from terminal.

Jan
![Screenshot_2021-04-08_06-56-36](https://user-images.githubusercontent.com/52598290/113955190-d5b14380-984d-11eb-9e91-9631f45733e9.png)

**Comment by insomniacno1** [comment]
So after I installed the 6.2.8rc2 version that is the latest available for 16.04, i looked in the menu and it were not there(then remebered that I removed it from there long time ago because double listing from snap and old version), so added it again and it started up. 

I tried Insert>media>scan>select source and this time it worked. So it would seem that on my system 16.04 newer versions of Libreoffice will not work with scan if installed through terminal. I will now test Latest and 6.4.7 App image to see if they work.

Screenshot attached from 6.2.8rc2
![Screenshot_2021-04-08_10-45-34](https://user-images.githubusercontent.com/52598290/113961273-5e34e180-9858-11eb-87a4-d33adea7209e.png)

**Comment by insomniacno1** [comment]
Ok, I'm getting really tired of this, yeah the screen shot shows that it finds my scanner(finally), unfortunately scan preview doesn't work as it keeps jumping back to default settings: Right 90mm Left: 54mm - Scan, source Platen, only scan Right: 90mm Left: 54mm and no matter how I set it to fit A4, it jumps back to default while scanning. ADF simplex and ADF Duplex come up with error if I try to generate a preview, and if I scan then it jumps back to default settings 90mm and 54mm. This is starting to drive me nuts. I tried to 
sudo apt purge scangearmp2
sudo apt update
sudo apt install scangearmp2

but that didn't change anything.





![Screenshot_2021-04-08_11-17-47](https://user-images.githubusercontent.com/52598290/113968151-208a8580-9865-11eb-9787-9a662686c1a4.png)
![Screenshot_2021-04-08_11-18-01](https://user-images.githubusercontent.com/52598290/113968166-25e7d000-9865-11eb-9d77-c60d2db5ebe3.png)
![Screenshot_2021-04-08_11-18-49](https://user-images.githubusercontent.com/52598290/113968172-27b19380-9865-11eb-93bc-137cd6bad90b.png)
![Screenshot_2021-04-08_11-19-29](https://user-images.githubusercontent.com/52598290/113968176-297b5700-9865-11eb-81a3-c452b5bdbaac.png)

**Comment by insomniacno1** [comment]
LO 6.4.7 App image, look a bit different but same behavior
![Screenshot_2021-04-08_12-58-41](https://user-images.githubusercontent.com/52598290/113971188-e02e0600-986a-11eb-832b-9d4e082c813a.png)
![Screenshot_2021-04-08_12-59-27](https://user-images.githubusercontent.com/52598290/113971192-e1f7c980-986a-11eb-90e7-c18a98b23e4d.png)
![Screenshot_2021-04-08_13-01-28](https://user-images.githubusercontent.com/52598290/113971194-e328f680-986a-11eb-86bb-54666a654e4f.png)
![Screenshot_2021-04-08_13-02-05](https://user-images.githubusercontent.com/52598290/113971196-e45a2380-986a-11eb-9d41-ca627ad3a528.png)

**Comment by insomniacno1** [comment]
LO 7.1 LibreOffice-fresh.basic-x86_64.AppImage doesn't even open
![Screenshot_2021-04-08_13-12-39](https://user-images.githubusercontent.com/52598290/113971937-4cf5d000-986c-11eb-8605-777f588a14ee.png)

**Comment by Ordissimo** [comment]
Ok,
Start by doing some tests without libreoffice, to check that the driver works correctly (probably already done).
Your installation complicates things a lot, it is obselete.
when you use snap the dialogs are managed by portal [Xenial Package](https://packages.ubuntu.com/search?suite=xenial-updates&arch=any&searchon=all&keywords=portal), you have to update it, there is a good chance that this is part of the problem. Here is the proposed patch [Github portal](https://github.com/flatpak/xdg-desktop-portal-gtk/pull/318) , June 19, 2020.
I'm afraid you will have a lot of trouble building the package on xenial.
Good luck!

**Comment by insomniacno1** [comment]
Hi Ordissimo, I went a bit further in my testing to see if the problem is the driver, which it might seem after this. I went to [https://libreoffice.soluzioniopen.com/old-versions/](url) and downloaded older versions of Libreoffice as App image(see screenshot), and each one of them behaved the excact same way as 6.4.7 - Newer versions don't ever show the scan dialog screen.

So even all the way back to LO  LibreOffice-3.6.7.2.help-x86_64.AppImage, when selecting the scan area 1 second later it jumps back to default which is Right: 90mm Left: 54mm - Selecting the Right and left and manually setting the size stay in place until you chose scan and then it jumps back to default and only scan that part of the document. This identical behavior, between numerous LO versions, suggest it's not an LO problem but the driver or the software behind it.

Scangear scan whole document as jpg files but cannot scan as PDF.
Simple Scan also.
Xsane also

Scangear has no preview, but both Simple Scan and Xsane has, and its working not jumping to default.

**Comment by insomniacno1** [comment]
just to be clear, I don't need the latest version of Libreoffice, i just need the scan to work, that whether LO is installed as App image, Snap or normal(I do prefer that one) :-) So I could easily stay with 6.4.7 App image or the latest for 16.04, 6.2.8rc2.

**Comment by insomniacno1** [comment]
I'm back on LO  6.2.8.2( 6.2.8rc2) Installed via Ubuntu Software centre(Not Gnome Software),last and latest version for 16.04 - 
same behavior.

**Comment by insomniacno1** [comment]
Just tried to scan again in 6.2.8.2 see screenshot below.

Also realized that I made a mistake in my description of the problem, the correct is:

Inser>Media>scan>select source: Select the scan area by adjusting by mouse cursor, 1 second later it jumps back to default which is Right: 90mm **Bottom:** 54mm - Selecting the Right and **Bottom** and manually setting the size, it stay in place until you chose scan and then it jumps back to default(Right: 90mm **Bottom:** 54mm) and only scan that part of the document.

It must be a problem with the canon_pixma driver
![Screenshot_2021-04-08_12-58-41](https://user-images.githubusercontent.com/52598290/114131825-e1783500-9935-11eb-932e-c24995803660.png)
![Screenshot_2021-04-08_12-59-27](https://user-images.githubusercontent.com/52598290/114131837-e4732580-9935-11eb-9cf6-4f2cc2cdac71.png)
![Screenshot_2021-04-08_13-01-28](https://user-images.githubusercontent.com/52598290/114131841-e63ce900-9935-11eb-9e8b-1ff13cba8c5a.png)
![Screenshot_2021-04-08_13-02-05](https://user-images.githubusercontent.com/52598290/114131847-e937d980-9935-11eb-8f68-a71ba1f8e4c3.png)

**Comment by insomniacno1** [comment]
this is how it was suppose to look like(Scanned with Scangear
![test jp](https://user-images.githubusercontent.com/52598290/114132078-4895e980-9936-11eb-87b3-eab6184207c7.jpg)
)

**Comment by insomniacno1** [comment]
Thread on Document Foundation's mailing list for Libreoffice bugs

[http://document-foundation-mail-archive.969070.n3.nabble.com/LO-not-finding-my-scanner-td4232392i20.html#a4298602](url)

**Comment by Ordissimo** [comment]
Hi @insomniacno1,
Ok, I reproduced your problem, I will look at it this weekend!
Don't touch your libreoffice installation anymore.

**Comment by insomniacno1** [comment]
Hi Ordissimo, I will not touch it, I'm using 6.2.8.2 normal install from
Ubuntu Software Centre and will stay on that version.

Thank you in advance 😊

Med venlig hilsen / With kind regards

Jan Brøndum Johansson

**Comment by Ordissimo** [comment]
I just updated the launchpad, can you test?

**Comment by Ordissimo** [comment]
No feedback !

**Comment by insomniacno1** [comment]
Hi Odissimo, I'm sorry I have not been able or had energy to test, both my girlfriend and I have been in hospital with Dengue hemoradic fever - not fun and she could have died, I'm bigger so it affected me differently. I'm testing now.

**Comment by insomniacno1** [comment]
Hi Odissimo, I'm sorry i have not been able or had energy to test, both my girlfriend and I have been in hospital with Dengue hemoradic fever - not fun and she could have died, I'm bigger so it affected me differently. I'm testing now. 

It's almost there, but the scan area is still not good, it changes to a fixed size Right: 209 mm Bottom: 296 mm - which is not A4, since A4 is Right: 210 mm Bottom: 297.

Even if I change the scan area to something smaller, then it jumps back to 209x296 - that takes the option of scanning a particular area out of the equation.

So what need to be fixed is the Scan area, so that "size set by user" stay in place when scanning, and the size is not "fixed".

Request: Is it possible to implement Standard international paper sizes like on the link below, so there is an  option is to chose fixed size or set Scan area manually: 

[https://www.neenahpaper.com/resources/paper-101/international-sizes](url)

Thank you for all your help on this.

Jan

**Comment by insomniacno1** [comment]
Moved to [#39](https://github.com/Ordissimo/scangearmp2/pull/39)
